### ISSUE TITLE
Switch to the MIDI.jl and ditch libmidi ?

### ISSUE THREAD

**Issue by Datseris** [JuliaMusic/Mplay.jl#9]
[MIDI.jl](https://github.com/JuliaMusic/MIDI.jl) is a well tested (on all OS), [well documented](https://juliamusic.github.io/JuliaMusic_documentation.jl/latest/midi/io/) and easy to use package for reading midi files. It also offers robust support for `Notes`, in the Julian way.

Most importantly, **it is written purely in Julia and has 0 dependencies and 0 external libraries.**

What would it take for Mplay to use MIDI.jl instead of libmidi? I am guessing some kind of 'streaming loading' interface? If @jheinen could have a look at MIDI.jl and tell me what would be necessary, I'd be happy to do some work to switch there.

**Comment by jheinen** [comment]
`libmidi` is not use to read MIDI files. It's use for MIDI device I/O. Could also be implemented in pure Julia, but does not make sense.

**Comment by Datseris** [comment]
Yeah then it makes sense. In MIDI.jl there has always been some desire for some stream based interface: https://github.com/JuliaMusic/MIDI.jl/issues/32

but it hasn't happened and I am not sure it ever will. We can revive this if this ever happens.
